name: Reproducible build

on:
  push:
    branches:
    - main
    - 'releases/*'
  pull_request:
    branches:
    - '*'

env:
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}

jobs:
  check_build_reproducibility:
    name: 'Check build reproducibility'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Cache Gradle wrapper and dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches/
          ~/.gradle/wrapper/dists
        key: assemble-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', '**/gradle.properties', 'gradle/**', 'buildSrc/src/main/**') }}
        restore-keys: |
          assemble-${{ runner.os }}-gradle-
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Prepare JDK16 env var
      shell: bash
      run: echo "JDK16=$JAVA_HOME" >> $GITHUB_ENV
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build and compare checksums
      shell: bash
      run: |
        ./gradlew javaToolchains -Porg.gradle.java.installations.auto-download=false
        ./src/checkBuildReproducibility.sh
